fix: use official color:lerp implementation if possible
TomDotBat/pixel-ui pull request #56
Opened 2024-07-03 16:22 UTC by JustPlayerDE

With garrysmod version 2024.06.28 there is a new official colorObj:Lerp() method which is not directly compatible with pixel's definition as the parameters are swapped.
Wiki Page: https://wiki.facepunch.com/gmod/Color:Lerp

The new Lerp method does not seem to be on default branch right now, for this case I have left the old pixel ui implementation as a replacement with the parameters swapped but with backwards compatibility and deprecation warning until the new implementation gets merged to garrysmod main.

Addons using the original pixel ui implementation may break with this change after the garrysmod update.

2024-07-03 16:25 UTC, TomDotBat requested changes
Looks good, not sure I like the idea of throwing an ErrorNoHalt on every call considering this method is generally used every frame.

2024-07-03 16:45 UTC, JustPlayerDE commented
> Looks good, not sure I like the idea of throwing an ErrorNoHalt on every call considering this method is generally used every frame.

I would say this is fine considering that this is a thing that should be updated as fast as possible, otherwise real errors will be thrown ever frame anyways in the future but with actually stopping the stack too (causing actual errors like breaking the entire hud)

I can make it throw only once though. as soon as a developer sees the initial error it should be clear enough I guess.

2024-07-03 17:28 UTC, Lythium4848 approved these changes

2024-07-04 09:13 UTC, TomDotBat approved these changes

2024-07-04 09:13 UTC, merged